name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install nodejs dependecies and build
        run: npm install && npm run build
      - name: Remove node_modules with dev dependecies
        run: rm -rf node_modules/
      - name: Install production dependecies
        run: npm install --production
      # the bluid flow is not redundant, it is necessary to get the small package size possible
      - name: Deploy
        id: deploy
        working-directory: ./infra
        run: terraform apply -auto-approve